# Diabetes Data Set

Dataset file: 'diabetes.data'  
Reference link for description of dataset: https://www4.stat.ncsu.edu/~boos/var.select/diabetes.html

### Preview of the Data Set

Load the data set.

a) Analyse the data set. Print the number of features, feature names, data types of the features, number of data points and the values of the first 10 data points.

In [3]:
import pandas as pd
import numpy as np

In [7]:
#df1=pd.read_data("diabetes.data")
df1=pd.read_csv("C:/Users/vishn/OneDrive/Desktop/Data Analytics Lab/Week 3/diabetes.data", sep="	")

In [8]:
df1.head(n = 10)
#diabetes = datasets.load_diabetes()

   AGE  SEX   BMI     BP   S1     S2    S3    S4      S5  S6    Y
0   59    2  32.1  101.0  157   93.2  38.0  4.00  4.8598  87  151
1   48    1  21.6   87.0  183  103.2  70.0  3.00  3.8918  69   75
2   72    2  30.5   93.0  156   93.6  41.0  4.00  4.6728  85  141
3   24    1  25.3   84.0  198  131.4  40.0  5.00  4.8903  89  206
4   50    1  23.0  101.0  192  125.4  52.0  4.00  4.2905  80  135
5   23    1  22.6   89.0  139   64.8  61.0  2.00  4.1897  68   97
6   36    2  22.0   90.0  160   99.6  50.0  3.00  3.9512  82  138
7   66    2  26.2  114.0  255  185.0  56.0  4.55  4.2485  92   63
8   60    2  32.1   83.0  179  119.4  42.0  4.00  4.4773  94  110
9   29    1  30.0   85.0  180   93.4  43.0  4.00  5.3845  88  310

In [9]:
df1.shape

(442, 11)

In [10]:
df1.dtypes

AGE      int64
SEX      int64
BMI    float64
BP     float64
S1       int64
S2     float64
S3     float64
S4     float64
S5     float64
S6       int64
Y        int64
dtype: object

In [11]:
for col in df1.columns: 
    print(col)

AGE
SEX
BMI
BP
S1
S2
S3
S4
S5
S6
Y

In [12]:
df = df1.drop(['Y'], axis =1)

In [13]:
df

     AGE  SEX   BMI      BP   S1     S2    S3    S4      S5   S6
0     59    2  32.1  101.00  157   93.2  38.0  4.00  4.8598   87
1     48    1  21.6   87.00  183  103.2  70.0  3.00  3.8918   69
2     72    2  30.5   93.00  156   93.6  41.0  4.00  4.6728   85
3     24    1  25.3   84.00  198  131.4  40.0  5.00  4.8903   89
4     50    1  23.0  101.00  192  125.4  52.0  4.00  4.2905   80
5     23    1  22.6   89.00  139   64.8  61.0  2.00  4.1897   68
6     36    2  22.0   90.00  160   99.6  50.0  3.00  3.9512   82
7     66    2  26.2  114.00  255  185.0  56.0  4.55  4.2485   92
8     60    2  32.1   83.00  179  119.4  42.0  4.00  4.4773   94
9     29    1  30.0   85.00  180   93.4  43.0  4.00  5.3845   88
10    22    1  18.6   97.00  114   57.6  46.0  2.00  3.9512   83
11    56    2  28.0   85.00  184  144.8  32.0  6.00  3.5835   77
12    53    1  23.7   92.00  186  109.2  62.0  3.00  4.3041   81
13    50    2  26.2   97.00  186  105.4  49.0  4.00  5.0626   88
14    61    1  24.0   91.00  202  115.4  72.0  3.00  4.2905   73
15    34    2  24.7  118.00  254  184.2  39.0  7.00  5.0370   81
16    47    1  30.3  109.00  207  100.2  70.0  3.00  5.2149   98
17    68    2  27.5  111.00  214  147.0  39.0  5.00  4.9416   91
18    38    1  25.4   84.00  162  103.0  42.0  4.00  4.4427   87
19    41    1  24.7   83.00  187  108.2  60.0  3.00  4.5433   78
20    35    1  21.1   82.00  156   87.8  50.0  3.00  4.5109   95
21    25    2  24.3   95.00  162   98.6  54.0  3.00  3.8501   87
22    25    1  26.0   92.00  187  120.4  56.0  3.00  3.9703   88
23    61    2  32.0  103.67  210   85.2  35.0  6.00  6.1070  124
24    31    1  29.7   88.00  167  103.4  48.0  4.00  4.3567   78
25    30    2  25.2   83.00  178  118.4  34.0  5.00  4.8520   83
26    19    1  19.2   87.00  124   54.0  57.0  2.00  4.1744   90
27    42    1  31.9   83.00  158   87.6  53.0  3.00  4.4659  101
28    63    1  24.4   73.00  160   91.4  48.0  3.00  4.6347   78
29    67    2  25.8  113.00  158   54.2  64.0  2.00  5.2933  104
..   ...  ...   ...     ...  ...    ...   ...   ...     ...  ...
412   69    1  34.3  113.00  200  123.8  54.0  4.00  4.7095  112
413   34    1  26.3   87.00  197  120.0  63.0  3.00  4.2485   96
414   71    2  27.0   93.33  269  190.2  41.0  6.56  5.2417   93
415   47    1  27.2   80.00  208  145.6  38.0  6.00  4.8040   92
416   41    1  33.8  123.33  187  127.0  45.0  4.16  4.3175  100
417   34    1  33.0   73.00  178  114.6  51.0  3.49  4.1271   92
418   51    1  24.1   87.00  261  175.6  69.0  4.00  4.4067   93
419   43    1  21.3   79.00  141   78.8  53.0  3.00  3.8286   90
420   55    1  23.0   94.67  190  137.6  38.0  5.00  4.2767  106
421   59    2  27.9  101.00  218  144.2  38.0  6.00  5.1874   95
422   27    2  33.6  110.00  246  156.6  57.0  4.00  5.0876   89
423   51    2  22.7  103.00  217  162.4  30.0  7.00  4.8122   80
424   49    2  27.4   89.00  177  113.0  37.0  5.00  4.9053   97
425   27    1  22.6   71.00  116   43.4  56.0  2.00  4.4188   79
426   57    2  23.2  107.33  231  159.4  41.0  5.63  5.0304  112
427   39    2  26.9   93.00  136   75.4  48.0  3.00  4.1431   99
428   62    2  34.6  120.00  215  129.2  43.0  5.00  5.3660  123
429   37    1  23.3   88.00  223  142.0  65.0  3.40  4.3567   82
430   46    1  21.1   80.00  205  144.4  42.0  5.00  4.5326   87
431   68    2  23.5  101.00  162   85.4  59.0  3.00  4.4773   91
432   51    1  31.5   93.00  231  144.0  49.0  4.70  5.2523  117
433   41    1  20.8   86.00  223  128.2  83.0  3.00  4.0775   89
434   53    1  26.5   97.00  193  122.4  58.0  3.00  4.1431   99
435   45    1  24.2   83.00  177  118.4  45.0  4.00  4.2195   82
436   33    1  19.5   80.00  171   85.4  75.0  2.00  3.9703   80
437   60    2  28.2  112.00  185  113.8  42.0  4.00  4.9836   93
438   47    2  24.9   75.00  225  166.0  42.0  5.00  4.4427  102
439   60    2  24.9   99.67  162  106.6  43.0  3.77  4.1271   95
440   36    1  30.0   95.00  201  125.2  42.0  4.79  5.1299   85
441   36    1  19.6   71.00  250  133.2  97.0  3.00  4.5951   92

[442 rows x 10 columns]

### Training and Testing Data Sets

b) Split the data set into training and testing data set with a 80:20 ratio.

(Hint: What precautions must you take before you split the data set?)

In [14]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df, df1.Y, test_size=0.2, random_state=0)

### Linear Regression

c) Using linear regression, seek a model for the response of interest ($Y$), as a function of the baseline variables such as age, sex, body mass index, etc. Compute the training error and testing error.

In [18]:
from sklearn.metrics import mean_squared_error
model = LinearRegression()
model.fit(X_train, y_train)
y_train_predicted = model.predict(X_train)
y_test_predicted = model.predict(X_test)
rmse_train = mean_squared_error(y_train, y_train_predicted)
rmse_test = mean_squared_error(y_test, y_test_predicted)
print("Train Error: ",rmse_train,"\n","Test Error: ",rmse_test)

Train Error:  2734.7508990757424
 Test Error:  3424.259334298694

### Data Preprocessing

d) Normalize the data set and perform linear regression again. Compute the training error and testing error. Comment.

In [19]:
from sklearn import preprocessing

In [20]:
df3 = sklearn.preprocessing.normalize(df1)

In [21]:
df3 = pd.DataFrame(df3)

In [22]:
df4 = df3.drop(df3.columns[10], axis =1)

In [23]:
X_train, X_test, y_train, y_test = train_test_split(df4, df3[10], test_size=0.2, random_state=0)

In [24]:
model = LinearRegression()
model.fit(X_train, y_train)
y_train_predicted = model.predict(X_train)
y_test_predicted = model.predict(X_test)
rmse_train = mean_squared_error(y_train, y_train_predicted)
rmse_test = mean_squared_error(y_test, y_test_predicted)
print("Train Error: ",rmse_train,"\n","Test Error: ",rmse_test)

Train Error:  0.0015615770552449009
 Test Error:  0.0016164253245794654

In [25]:
model.coef_

array([-0.35540996, -1.21011049, -0.56017467, -0.64224831, -1.25032664,
       -0.54237399, -0.63607066, -3.66731231,  8.00368537, -0.63798254])

### Feature Reduction

e) Rank the features in order of importance (based on the study in d)). Comment.

S5,S4, S1, SEX, BP,S6, S3,BMI,S2, AGE. The higher the absolute value of coefficients the more important the parameter is.

### Polynomial Regression

f) Repeat the exercise in d) with quadratic features. List the features you would add to the existing data set. Compute the training error and the testing error. Comment.

In [26]:
df5 = df3.drop(df3.columns[[10,7,3,6,1]], axis =1)

In [27]:
X_train, X_test, y_train, y_test = train_test_split(df5, df3[10], test_size=0.2, random_state=0)

In [29]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
polynomial_features = PolynomialFeatures(degree=2)
X_poly = polynomial_features.fit_transform(X_train)
model = LinearRegression()
model.fit(X_poly, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [30]:
from sklearn.preprocessing import PolynomialFeatures
polynomial_features= PolynomialFeatures(degree=2)
x_train_poly = polynomial_features.fit_transform(X_train)
model = LinearRegression()
model.fit(x_train_poly, y_train)
y_train_poly_pred = model.predict(x_train_poly)
x_test_poly = polynomial_features.fit_transform(X_test)
y_test_poly_pred = model.predict(x_test_poly)
mse_train = (mean_squared_error(y_train,y_train_poly_pred))
error_train = (mse_train)
mse_test = (mean_squared_error(y_test,y_test_poly_pred))
error_test = (mse_test)
print("Train Error : ",error_train,"\n","Test Error : ",error_test)

Train Error :  0.001341577535735313
 Test Error :  0.0017168762006729112

Polynomial Regression is much better as it has beter score.